import { useCallback, useEffect, useMemo, useState } from "react";
import { admin } from "../api";
import type { Role, UserRow } from "../types";

type Props = { onOpenUser: (userId: string) => void };
type SortKey = "created_at" | "full_name" | "user_id" | "email";
const money = (n: number) => n.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const date = (value: string | null) => value ? value.slice(0, 10) : "—";
const label = (value: string | null | undefined) => value ? value.charAt(0).toUpperCase() + value.slice(1) : "—";

function Badge({ children, tone = "neutral" }: { children: React.ReactNode; tone?: string }) { return <span className={`user-badge ${tone}`}>{children}</span>; }

export default function UsersPage({ onOpenUser }: Props) {
  const [users, setUsers] = useState<UserRow[]>([]); const [total, setTotal] = useState(0); const [page, setPage] = useState(1); const perPage = 10;
  const [q, setQ] = useState(""); const [role, setRole] = useState(""); const [accountStatus, setAccountStatus] = useState(""); const [paymentStatus, setPaymentStatus] = useState(""); const [competitionStatus, setCompetitionStatus] = useState(""); const [university, setUniversity] = useState("");
  const [sort, setSort] = useState<SortKey>("created_at"); const [order, setOrder] = useState<"asc" | "desc">("desc"); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [busyId, setBusyId] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const result = await admin.listUsers({ page: 1, per_page: 100, q: q.trim() || undefined, role: role || undefined, university: university || undefined, sort, order }); let rows = result.users; if (accountStatus) rows = rows.filter((u) => (u.account_status || "").toLowerCase() === accountStatus); if (paymentStatus) rows = rows.filter((u) => paymentStatus === "paid" ? u.is_paid : !u.is_paid); if (competitionStatus) rows = rows.filter((u) => (u.competition_status || "").toLowerCase() === competitionStatus); setUsers(rows.slice((page - 1) * perPage, page * perPage)); setTotal(accountStatus || paymentStatus || competitionStatus ? rows.length : result.total); } catch (e) { setError(e instanceof Error ? e.message : "Failed to load users."); } finally { setLoading(false); } }, [page, q, role, accountStatus, paymentStatus, competitionStatus, university, sort, order]);
  useEffect(() => { void load(); }, [load]);
  const totalPages = Math.max(1, Math.ceil(total / perPage)); const universities = useMemo(() => Array.from(new Set(users.map((u) => u.university).filter(Boolean))), [users]);
  const changeFilter = (setter: (value: string) => void, value: string) => { setter(value); setPage(1); }; const sortBy = (key: SortKey) => { setSort(key); setOrder(sort === key && order === "desc" ? "asc" : "desc"); setPage(1); }; const runAction = async (id: string, action: () => Promise<unknown>) => { setBusyId(id); setError(null); try { await action(); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Action failed."); } finally { setBusyId(null); } };
  return <div className="users-page">
    <div className="page-header users-heading"><div><h1>Users</h1><span className="muted">{total} users</span></div><button className="add-user-button" disabled title="User creation is managed through registration">+ Add User</button></div>
    {error && <div className="error-banner users-error">{error}</div>}
    <div className="users-toolbar"><input className="users-search" value={q} onChange={(e) => changeFilter(setQ, e.target.value)} placeholder="Search name, email, or ID…" /><div className="users-filter-row"><select value={role} onChange={(e) => changeFilter(setRole, e.target.value)}><option value="">All Roles</option><option value="admin">Admin</option><option value="student">Student</option></select><select value={accountStatus} onChange={(e) => changeFilter(setAccountStatus, e.target.value)}><option value="">All Account Status</option><option value="active">Active</option><option value="suspended">Suspended</option></select><select value={paymentStatus} onChange={(e) => changeFilter(setPaymentStatus, e.target.value)}><option value="">All Payment Status</option><option value="paid">Paid</option><option value="pending">Pending</option></select><select value={competitionStatus} onChange={(e) => changeFilter(setCompetitionStatus, e.target.value)}><option value="">All Competition Status</option><option value="enrolled">Enrolled</option><option value="withdrawn">Withdrawn</option></select><select value={university} onChange={(e) => changeFilter(setUniversity, e.target.value)}><option value="">All Universities</option>{universities.map((u) => <option key={u} value={u!}>{u}</option>)}</select></div><button className="refresh-users" onClick={() => void load()}>Refresh</button></div>
    <div className="users-table-wrap">{loading ? <div className="users-loading"><span className="spinner" /> Loading users…</div> : <table className="users-table"><thead><tr><th onClick={() => sortBy("created_at")}>Joined {sort === "created_at" ? (order === "desc" ? "▼" : "▲") : ""}</th><th onClick={() => sortBy("full_name")}>Name</th><th>ID</th><th>Email</th><th>Role</th><th>Account<br />Status</th><th>Payment<br />Status</th><th>Competition</th><th>Round</th><th>Portfolio</th><th>Return</th><th>Score</th><th>Actions</th></tr></thead><tbody>{users.map((u) => <tr key={u.user_id}><td>{date(u.created_at)}</td><td><button className="user-name-link" onClick={() => onOpenUser(u.user_id)}>{u.full_name || u.email}</button></td><td className="user-id">{u.user_id}</td><td className="user-email">{u.email}</td><td><Badge tone={u.role === "admin" ? "admin" : "student"}>{u.role.toUpperCase()}</Badge></td><td><Badge tone={u.account_status === "suspended" ? "danger" : "success"}>{label(u.account_status || "active")}</Badge></td><td><Badge tone={u.is_paid ? "success" : "warning"}>{u.is_paid ? "Paid" : "Pending"}</Badge></td><td>{u.competition_status ? <Badge tone="success">{label(u.competition_status)}</Badge> : "—"}</td><td>{u.competition_status ? "Round 1" : "—"}</td><td>{money(u.portfolio_value)}</td><td className={u.return_pct >= 0 ? "positive-text" : "negative-text"}>{u.return_pct >= 0 ? "+" : ""}{u.return_pct.toFixed(2)}%</td><td>{u.latest_final_score ?? 0}</td><td><details className="user-actions"><summary>⋮</summary><div className="user-actions-menu"><button onClick={() => onOpenUser(u.user_id)}>View details</button><button disabled={busyId === u.user_id} onClick={() => void runAction(u.user_id, () => admin.updateUserAccount(u.user_id, { is_paid: !u.is_paid }))}>{u.is_paid ? "Mark unpaid" : "Mark paid"}</button><button disabled={busyId === u.user_id} onClick={() => void runAction(u.user_id, () => admin.updateUserAccount(u.user_id, { account_status: u.account_status === "suspended" ? "active" : "suspended" }))}>{u.account_status === "suspended" ? "Reactivate" : "Suspend"}</button><button disabled={busyId === u.user_id} onClick={() => void runAction(u.user_id, () => admin.updateUserCompetition(u.user_id, { action: u.competition_status === "enrolled" ? "withdraw" : "enroll", competition_round: "Round 1" }))}>{u.competition_status === "enrolled" ? "Withdraw" : "Enroll"}</button><button disabled={busyId === u.user_id} onClick={() => void runAction(u.user_id, () => admin.updateUser(u.user_id, { role: (u.role === "admin" ? "student" : "admin") as Role }))}>{u.role === "admin" ? "Make student" : "Make admin"}</button></div></details></td></tr>)}</tbody></table>}{!loading && users.length === 0 && <div className="empty users-empty">No users match the current filters.</div>}</div>
    <div className="users-footer"><span>Showing {users.length ? (page - 1) * perPage + 1 : 0} to {Math.min(page * perPage, total)} of {total} users</span><div className="pagination"><button disabled={page <= 1} onClick={() => setPage(page - 1)}>‹</button>{Array.from({ length: Math.min(totalPages, 3) }, (_, i) => i + 1).map((n) => <button className={page === n ? "current" : ""} key={n} onClick={() => setPage(n)}>{n}</button>)}<button disabled={page >= totalPages} onClick={() => setPage(page + 1)}>›</button></div></div>
  </div>;
}
